---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deploy-new-d840b523
  labels:
    app: next-deploy-new-d840b523
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: next-deploy-new-d840b523
  template:
    metadata:
      labels:
        app: next-deploy-new-d840b523
    spec:
      containers:
        - name: next-deploy-new-d840b523
          image: docker.io/phengbunath/next-deploy-new-d840b523:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
